export const SEARCH_BANNER = 'search_banner'
export const RECOMMEND_MUSIC_LIST = 'recommend_music_list'
export const UPDATEPLAYLISTID = 'update_play_list_id'
export const PLAY_LIST_DETAIL = 'play_list_detail'
export const SONG_DETAIL = 'song_detail'
export const UPDATE_MUSIC_LIST = 'update_music_list'
export const UPDATE_PLAY_STATUS = 'update_play_status'
export const PLAYER_SHOW = 'player_show'